name: Docker Image CI

on:
  push:
    branches: [ "main" ] # Runs after commit
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: # Step 1 : Get branch name , Step 2 : Declare SHA, Step 3 : Build, tag and push to ecr
    - name: checkout
      uses: actions/checkout@v3
      with:
        repository: 'dordiamant47/Whist'
      
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
      
    - name: Declare sha
      id: vars
      shell: bash
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "us-east-1"
      
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Build, tag, and push the image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: "dorwhist"
        TAG: "latest"
      run: |
        echo "Pushing image to ECR..."
        cd ./Whist/
        docker build --tag $ECR_REGISTRY/$ECR_REPOSITORY:latest --tag "my-image-${{ steps.extract_branch.outputs.branch }}-${{ steps.vars.outputs.sha_short }}" .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push "my-image-${{ steps.extract_branch.outputs.branch }}-${{ steps.vars.outputs.sha_short }}"
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$TAG"
